### GET USER INFORMATION
GET https://spa-zalo-mini-app-server-6.onrender.com/api/users/user-info/12345648999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjczMzkyMTgsImV4cCI6MTcyNzM0MjgxOCwiYXVkIjoiNjZmNTFhZDIwZjNjZGU5MTVkMmU4NGQzIn0.16QoF2meCkRCKCzFZu1JV8OKU_yOhsrdKobRnqnCcDo

### UPDATE USER INFORMATION
PUT http://localhost:8080/api/users/update-user-info/12345648999
Content-Type: application/json
Authorization: Bearer token_here

{
    "name": "Nguyen Van B",
    "phone": "0123456789"
}
