### GET PLAY COUNT
GET http://localhost:8080/api/minigame/play-count
Content-Type: application/json

{
    "userId": "objectId"
}

### PLAY MINIGAME
POST http://localhost:8080/api/minigame/play
Content-Type: application/json

{
    "userId": "objectId"
}

### UPDATE POINTS
PUT http://localhost:8080/api/minigame/update-points
Content-Type: application/json

{
    "userId": "objectId",
    "points": 10
}

### UPDATE PLAY COUNT
PUT http://localhost:8080/api/minigame/update-play-count
Content-Type: application/json

{
    "userId": "objectId",
    "playCount": 3
}