### GET USER INFORMATION
GET https://localhost:8080/api/users/user-info/12345648999
Authorization: Bearer token_here

### UPDATE USER INFORMATION
PUT http://localhost:8080/api/users/update-user-info/12345648999
Content-Type: application/json
Authorization: Bearer token_here

{
    "name": "Nguyen Van A",
    "phone": "0123456789"
}
