### GET USER INFORMATION BASED ON ZALO ID
GET https://localhost:8080/api/users/user-info/:zaloId
Authorization: Bearer token_here

### UPDATE USER INFORMATION BASED ON ZALO ID
PUT http://localhost:8080/api/users/update-user-info/:zaloId
Content-Type: application/json
Authorization: Bearer token_here

{
    "name": "Nguyen Van A",
    "phone": "0123456789"
}

### UPDATE USER PHONENUMBER BASED ON ZALO ID
PUT http://localhost:8080/api/users/update-user-phone/:zaloId
Content-Type: application/json
Authorization: Bearer token_here
phone-token: phone_token_here
zalo-access-token: zalo_access_token_here