
GET http://localhost:8080
Authorization: Bearer token_here

### REGISTER ROUTE USER
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "zaloId": "123456789",
    "role": "user",
    "name": "Nguyễn Văn A",
    "urlImage": ""
}

### REGISTER ROUTE ADMIN CMS
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "role": "admin"
}

### LOGIN ROUTE USER
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "zaloId": "123456789",
    "role": "user"
}

### LOGIN ROUTE ADMIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456",
    "role": "admin"
}


### REFRESH TOKEN
POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": ""
}

### LOGOUT ROUTE
DELETE http://localhost:8080/auth/logout
Content-Type: application/json

{
    "refreshToken": ""
}